### ISSUE TITLE
Atom feed needs more testing and maybe fixing

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1015]
This problem occurred prior to conversion to feedgen library and persists after the change.

Using Freeder on an Android phone, the message "MoinMoin feels unhappy"  frequently appears when accessing 

    <moin2 wiki url>/+feed/atom or <moin2 wiki url>/+feed/atom/Home

When given the same url, Chrome and Opera display the raw XML file, Firefox presents a download dialog.

The problem is in /apps/feed/views.py:

            try:
                hl_item = Item.create(name, rev_id=this_revid)
                if previous_revid is not None:
                    # HTML diff for subsequent revisions
                    previous_rev = item[previous_revid]
                    content = hl_item.content._render_data_diff_atom(previous_rev, this_rev)
                else:
                    # full html rendering for new items
                    content = render_template('atom.html', get='first_revision', rev=this_rev,
                                              content=Markup(hl_item.content._render_data()), revision=this_revid)
                content_type = 'html'
            except Exception as e:
                logging.exception("content rendering crashed")
                content = _('MoinMoin feels unhappy.')
                content_type = 'text'

**Comment by sblondon** [comment]
The try/except block did not change during the migration from `flask.atom` to `feedgen` library. So the bug is still there.

I have two hypothesis : 
- Freeder does not use the correct URL (for example by adding parameters which are badly interpreted)
- the code is called if 'content is None' https://github.com/moinwiki/moin/blob/9af32d3cd56b32792bb804df081add97e05b1b84/src/moin/apps/feed/views.py#L55 This occurs if `revs` is an empty list, which is about searching in cached modifications if I understand properly. Perhaps you see the error with Freeder because it downloaded several times along the day the modifications so sometimes there are no modification) than a browser. Did you try with/without cache/private mode in browser? Or with `wget` two times  in interval of few seconds?

**Comment by RogerHaase** [comment]
My initial report was unclear. The MoinMoin is unhappy message is also in the raw XML files and the downloaded file.

**Comment by sblondon** [comment]
Adding info in the logging step (probably via `stack_info` or `exc_info`) could help to understand the bug.

Are you interested by a PR?

**Comment by RogerHaase** [comment]
yes

**Comment by RogerHaase** [comment]
Does the above imply that you cannot reproduce the error? On a freshly loaded sample wiki with one small change I get:

`
  <entry>
    <id>http://127.0.0.1:8080/+show/+7d98eeb56f5b4044a64d8d69d6caab1b/Home</id>
    <title>127.0.0.1</title>
    <updated>2020-05-23T17:01:52.139904+00:00</updated>
    <author>
      <name>127.0.0.1</name>
    </author>
    <link href="http://127.0.0.1:8080/+show/+7d98eeb56f5b4044a64d8d69d6caab1b/Home" rel="alternate"/>
    <summary>MoinMoin feels unhappy.</summary>
  </entry>
</feed>
`

I am on windows - another windows only error?

**Comment by sblondon** [comment]
I reproduce the error on Linux (Debian testing).

I tried to add logs but I'm not convinced: I don't see more info with `exc_info=True` and `stack_info=True` is more noisy than useful in this usecase.

However I have a patch to fix the error (https://github.com/moinwiki/moin/pull/1016).

I agree that adding unit test would be a good idea to protect against regression.
