### ISSUE TITLE
move CI to github actions

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#1082]
about: https://news.ycombinator.com/item?id=25338983

example: https://github.com/borgbackup/borg/blob/master/.github/workflows/ci.yml

**Comment by RogerHaase** [comment]
CI build not running after last pull request.

Went to travis-ci.com, signed up, ordered a free account, received 10,000 credits for MoinMoin Wiki Engine.

There is no option to rerun build on pull request page:  https://github.com/moinwiki/moin/pull/1106

Made a few CSS changes, amended last commit and pushed. CI build did not restart as before. No obvious way to restart CI build.

Not sure what I did, now I get a warning message:

    Builds have been temporarily disabled for private and public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance.

    -190 available credits (purchase date: March 18, 2021)
    You have used 10190 of 10000 credits
    -190 available

**Comment by ThomasWaldmann** [comment]
10000 sounds much, but isn't. I just moved away from travis-ci for other projects.

**Comment by RogerHaase** [comment]
Assuming the start to fixing this issue is to remove all Travis CI stuff...

Following https://remarkablemark.org/blog/2021/03/15/github-remove-travis-ci/#:~:text=Revoke%20Travis%20CI%20from%20Account%20settings%20%3E%20Applications%3A,settings%2C%20check%20if%20Travis%20CI%20is%20added%20in%3A

Under Organization, Travis CI must be removed from 3rd party apps and github apps.  Nothing to do under Webhooks.

Under Repository Config, delete .travis.yml. Nothing to do under Branches and Webhooks.
