### ISSUE TITLE
m sample error

### ISSUE THREAD

**Issue by pktl** [moinwiki/moin#1083]
Hi everyone,

I wanted to try and install moin2, following the documentation [here](https://github.com/moinwiki/moin/blob/master/docs/devel/development.rst) and [here](https://moin-20.readthedocs.io/en/latest/admin/install.html#installation-for-developers).

But I'm stuck already when I'm supposed to call `./m sample`.
Without activation of the virtual environment, I get `/bin/sh: moin: command not found`. After activating the virtual environment, I get 
```
2 Traceback (most recent call last):
18     raise error.ConfigurationError("No storage configuration specified! You need to define a namespace_mapping.")
19 moin.error.ConfigurationError: No storage configuration specified! You need to define a namespace_mapping.
22 Traceback (most recent call last):
38     raise error.ConfigurationError("No storage configuration specified! You need to define a namespace_mapping.")
39 moin.error.ConfigurationError: No storage configuration specified! You need to define a namespace_mapping.
```

I haven't found anything in the troubleshooting section of the documentation. So, what am I supposed to do?

And also: if it's necessary to activate the virtual environment, it should say so in the documentation.

Thanks in advance!

**Comment by RogerHaase** [comment]
Thanks for reporting the error.

I found 2 missing installation steps, corrected below:

"""
create your development environment
-----------------------------------

* if you do not have a github account, create one at https://github.com/
* fork the main repository: https://github.com/moinwiki/moin to your gh user
* clone your gh repo to your local development machine::
    cd <parent_directory_of_your_future_repo>
    git clone https://github.com/yourname/moin.git
* cd to repo root
    cd moin
* create the virtualenv and download packages::
    python quickinstall.py
* activate virtualenv
    . activate  # on windows: activate
* create a wiki instance and load sample data::
    ./m sample  # Windows: m sample
* start the built-in server::
    ./m run  # Windows: m run
* point your browser at http://127.0.0.1:8080/ to access your development
wiki
* key ctrl+C to stop the built-in server
"""

The traceback seems to be caused by a failure in quickinstall.py; this code
is not being run:

    def copy_config_files():
        if not os.path.isfile('wikiconfig.py'):
            shutil.copy('src/moin/config/wikiconfig.py', 'wikiconfig.py')
        if not os.path.isfile('intermap.txt'):
            shutil.copy('src/moin/config/intermap.txt', 'intermap.txt')
        if not os.path.isdir('wiki_local'):
            os.mkdir('wiki_local')

For the moment, you will have to workaround the issue by copying the 2
files to the wiki root and creating the wiki_local directory.

Once you do that, ./m sample and ./m run should work.

Roger Haase

**Comment by pktl** [comment]
Thanks, your workaround works.
I'll try and dig around a bit to find the cause of this failure. Do you have a suspicion?
(Can't promise anything, though. A lot of stuff is completely new to me.)

By the way: After creating the sample wiki, `intermap.txt` and `wikiconfig.py` show up as untracked files. Probably those should be added to `.gitignore` as well?

**Comment by RogerHaase** [comment]
Found error, will push a fix for docs and code in a few hours.

You are correct about additions to .gitignore, will push a fix for that as well.
