### ISSUE TITLE
line endings on text help files should be \r\n

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1390]
The text help files in /src/moin/help/en have \n line endings under version control. The size attribute in the .meta file is wrong, always higher than the actual file size. The sha1 attribute may be wrong, haven't checked.

If `moin dump-help -n en` or `moin item-get ...` is run on windows, then the output has \r\n line endings. The size attribute in the .meta file is correct.

`moin item-put ...`  changes the line endings of wiki text data files to \r\n, because html textareas have \r\n line endings. The meta file has no line endings.

moin dump-help and moin item-get should force \r\n line endings, and the help pages under version control should have \r\n line endings.

In theory this change should not impact unix based developers updating help files. The usual sequence would be to load help files, edit help files, dump help files, commit the changes, push.

**Comment by bylsmad** [comment]
@RogerHaase I don't believe this branch has done what you intended.  my guess is you have your gitconfig set up with `core.autocrlf true` which replaces \r\n  with \n when you add a file.  This setting is a good thing IMHO because it makes for ease of working with folks like myself who use Linux or MacOS for development, I have mine set to `core.autocrlf input`.  (see the repo compare which shows the .data files are unchanged https://github.com/moinwiki/moin/compare/master...RogerHaase:moin:help)

the options as I see them:

1. leave the files with \n in git and drop this branch...on your system they will check out with  \r\n on my system they will check out with \n.  #1389 fixes the issue with the conflict in the size attribute on both Windows and Linux systems, please see the latest version of test_modify_item in that branch.  test_modify_item contains a test which reproduced the lineending at end of file issue before the fix was introduced in that branch.  note that the size and sha1 are calculated after the line ending conversion in moin.cli.maint.modify_item._PutItem so on Linux the size and sha1 appear to be wrong if I calculate them using the files on disc, but they are seen as correct when I item-put
2. add a .gitattributes file to the repo which  specifies that .data are binary files and redo this branch.  We will still need the fix in #1389 in order to handle item-get followed by item-put for a text item in storage which does not have a line ending at the end, so I'm not sure what is gained by this? see https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows

Either way, I don't see anything gained by forcing \r\n in the .meta files as python handles the line endings cross-platform seamlessly already for json files

I vote for option 1

**Comment by RogerHaase** [comment]
My git setting is `core.autocrlf=input` and my favorite editors are set to save python files with \n line endings.

I think there is a bug in src/moin/cli/maint/modify_item.py where line 53 (line 61 has same issue)

    with open(meta_file, 'w', encoding='utf-8') as mf:

should be

    with open(meta_file, 'w', encoding='utf-8', newline='\r\n') as mf:

But I am OK with making it:

    with open(meta_file, 'w', encoding='utf-8', newline='\n') as mf:

The problem occurs when `moin dump-help` is run. By default, all of the versioned help files are currently overwritten with the OS's default line endings. (You should see similar problem on your MacOs. ) On windows, this confuses TortoiseGit into thinking all the help files have changed, but then refuses to stage the files because they haven't changed. 

Can we agree on adding `newline='\n'` as a compromise?

**Comment by bylsmad** [comment]
@RogerHaase ah now I understand thanks.

Yes `newline='\n'` works for me...I've added that to #1389 and adjusted the test appropriately.  tests are running in github action now.

**Comment by RogerHaase** [comment]
fixed by tests for cli, #1387 #1389

**Comment by bylsmad** [comment]
@RogerHaase I am eating crow today, the `newline=\r\n` that I thought was not needed caused failure in my own test.  https://github.com/bylsmad/moin/actions/runs/4667519456/jobs/8263425512

looks like the reference windows box for github action uses autocrlf=true

I will be humbly submitting a pull req for option 2 above then will be able to go fw with #1378 which is working already except for this failure
