### ISSUE TITLE
update help/welcome/users-Home.data

### ISSUE THREAD

**Issue by bylsmad** [moinwiki/moin#1416]
could we replace this with a wiki page describing what is the users namespace and what can be done here? as a beginner moin user the users namespace is mysterious to me.

**Comment by UlrichB22** [comment]
The intention of this Home item is to have a welcome message instead of the dialog to create a new item. 
This page will usually be replaced by the user with his own content.

IMO we should have a help system similar to the moin 1.9 help in https://moinmo.in/HelpContents and https://moinmo.in/HelpForUsers. The content in help/en is up to now only the part describing the different markup languages. 

Please see #1155 for the initial discussion on help.

**Comment by bylsmad** [comment]
@UlrichB22 to clarify - this issue is about /users/Home not /Home in the welcome files.

I added /users/Home to welcome in the scrapy-test branch because many of the help-en pages had links to it and the 404 response for /users/Home was causing failures in the scrapy test which were not meaningful.

In addition to causing failures in the scrapy test, when I first installed moin I was quite confused by the users namespace.  Particularly confusing was that clicking on the "user" link on /+admin/user page led me to a dialog to create a new item.  I think it would be of use for a fresh install to have some explanatory text at /users/Home about what this namespace is all about and what I'm supposed to be able to do here.

Perhaps what we need on the welcome users/Home is a link to a new page in help-en?

**Comment by RogerHaase** [comment]
I think a users/Home page would be helpful.  A thought not ready for prime time:

    = users/Home =

    Use this namespace to create your user home page using your login name as the name. 
    If you are logged in when you create/edit a page there will be a link to your home page
    near the bottom in the item credits.

    You are encouraged to fill your home page with any information about yourself
    that you are willing to share with other wiki users. There will be a contest for the most
    imaginative home page on the first of every month; winner will receive a certificate 
    suitable for framing.
