### ISSUE TITLE
WikiGroup: How to access "Extra Metadata (JSON)”?

### ISSUE THREAD

**Issue by wagner-intevation** [moinwiki/moin#1554]
To create a Group, I wanted to follow the documentation on WikiGroups: https://moin-20.readthedocs.io/en/latest/admin/configure.html#group-backend-configuration

> To create a WikiGroup that can be used in an ACL rule:
> 1. Create a wiki item with a name ending in “Group” (the content of the item is not relevant)
> 2. **Edit the metadata and add an entry for “usergroup” under the heading “Extra Metadata (JSON)”:**

But how is the step 2 supposed to work? Where can I edit the metadata and find the heading “Extra Metadata (JSON)”?

**Comment by RogerHaase** [comment]
Looks like I may have killed Groups accidently with removing  the “Extra Metadata (JSON)” in https://github.com/moinwiki/moin/issues/700. Where the thought was it was a bad idea to allow editors to change metadata.

Try reverting https://github.com/moinwiki/moin/commit/dd3532629f79074a651e6d16bf405e36ec8cbfb8. 
And fix line  51 of `items/__init__.py` to add JSON back in the import:

    from moin.forms import RequiredText, OptionalText, JSON, Tags, Names, validate_name, NameNotValidError

TODO:

* changed metadata will not get saved unless there is a change to the data
* The extra metadata should only be shown for items with names ending in Group
* See #1206, show extra metadata for WikiDict
* meta view filters out "group", must look at meta file to see group value
* The Extra Metadata input area should only allow "group", maybe labeled "Group Metadata", or maybe accept just a list of user names, no need for users to key in "group": .....
* rather than itemnames ending in Group, maybe this should use a "group" tag like templates uses "template"

Wagner do you want to work on this? Else I will assign to myself.

**Comment by wagner-intevation** [comment]
> rather than itemnames ending in Group, maybe this should use a "group" tag like templates uses "template"

Can't anyone assign any tag to an item? Group management should be an Admin-Privilege in my opinion.

> Wagner do you want to work on this? Else I will assign to myself.

Given the open questions and the required changes in the core, I'm hesitant, this will work. Some contributions to the feature and testing are possible for sure.
