### ISSUE TITLE
whoosh pickling error on item save

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#264]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/264) by RogerHaase (Bitbucket: [RogerHaase](https://bitbucket.org/RogerHaase), GitHub: [RogerHaase](https://github.com/RogerHaase)).**

The original report had attachments: PicklingError.txt

----------------------------------------

Sometimes after an apache restart, all attempts to save any items will result in a traceback (see attached PicklingError.txt).

Restarting apache eliminates the problem.

**Comment by ThomasWaldmann** [comment]
@RogerHaase Matt has a question on the whoosh issue tracker, see link in last post.

Can you still reproduce these issues as of now?

**Comment by RogerHaase** [comment]
Closing this as I think this is a Python 2.7.x issue caused by a cpickle/pickle incompatibility, not a whoosh or moin problem. Closed the whoosh issue: https://bitbucket.org/mchaput/whoosh/issues/314/picklingerror-cant-pickle-apache-windows-7

I can still reproduce the problem 100% of the time as described in the initial whoosh report with Python 2.7.13 and Windows 10.

Both of the easy workarounds described in the initial report still work.

Will retest if we ever get to Python 3.
