### ISSUE TITLE
auto-create storage / index if they do not exist?

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#272]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/272) by Thomas Waldmann (Bitbucket: [thomaswaldmann](https://bitbucket.org/thomaswaldmann), GitHub: [thomaswaldmann](https://github.com/thomaswaldmann)).**

----------------------------------------

On GAE (see gae branch, if not merged yet), the code detects whether there is already an index and if not, autocreates one.

Do we want this behaviour also on the non-GAE version?

Can it be a moin storage / whoosh storage independant check (so that the real check is in the storage implementation, not in moin highlevel code)?

**Comment by RogerHaase** [comment]
This issue was created prior to the quickinstall menu. Not mentioned above, but running "moin moin" prior to creating a wiki resulted in an esoteric traceback (still does). With the present menu system, the user gets a warning message if he tries to do a "./m run" prior to creating a wiki instance.

In recent instances where I received the "No wiki created" warning as part of testing, I had forgotten to restore test data or load the sample wiki data. So I think the warning message is more helpful than creating an empty wiki.

Closing this issue, see #824.
