### ISSUE TITLE
Search is broken due to names being a list.

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#364]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/364) by Ashutosh Singla (Bitbucket: [ashu1461](https://bitbucket.org/ashu1461), GitHub: [ashu1461](https://github.com/ashu1461)).**

----------------------------------------

The current item_name_analyzer, works given that item name is a single unicode value, fails in case the name is a list.

```
#!python

def item_name_analyzer():
    """
    Analyzer behaviour:

    Input: u"some item name", u"SomeItem/SubItem", u"GSOC2011"

    Output: u"some", u"item", u"name"; u"Some", u"Item", u"Sub", u"Item"; u"GSOC", u"2011"
    """
    iwf = MultiFilter(index=IntraWordFilter(mergewords=True, mergenums=True),
                      query=IntraWordFilter(mergewords=False, mergenums=False)
                     )
    analyzer = RegexTokenizer(r"\S+") | iwf | LowercaseFilter()
    return analyzer
```

So, the lookup and search views are broken due to this reason.

**Comment by RogerHaase** [comment]
There was a brief period of activity on https://github.com/whoosh-community/whoosh/issues

The whoosh 321 issue is closed https://github.com/whoosh-community/whoosh/issues/321

**Comment by RogerHaase** [comment]
Not sure what is broken here. If there is an item named OrangeTwo and OrangeTwo appears nowhere in the item content, summary, tags, etc., then a search for Orange or Two does not find the item. Is this the bug?

A search for OrangeTwo finds the item. 

A mitigating factor is the item name is likely to appear somewhere in the text, perhaps within an H1 tag. In that case a search for Orange or Two will find the item.

**Comment by RogerHaase** [comment]
This issue causes one problem mentioned in #1073. It causes missing hits on item name:

* Searching by name and name_exact results in many misses, one right way, many wrong ways.
  * name:AcornPress fails
  * name:acornpress fails
  * name:acorn AND name:press fails
  * name_exact:acornpress fails
  * name_exact:AcornPress succeeds

Help from the Whoosh team is unlikely, so a workaround is needed.

One way is to continue storing the metadata NAME attribute as is but stop using it as a search term (it is broken because NAME is a list). Add a new metadata attribute NAMES as a string created by joining the components of NAME. NAMES will be indexed, but not stored because the value is easily recreated from NAME.

This is an awkward solution but avoids changing a lot of code that pulls NAME from metadata expecting a list. The change is made harder because spaces are allowed within item names so creating NAME from NAMES is not a simple split on space characters.

**Comment by RogerHaase** [comment]
Another way is to use the approach described here: 

    https://whoosh.readthedocs.io/en/latest/indexing.html#indexing-and-storing-different-values-for-the-same-field

That way 'name' could be stored as a list of strings but indexed as a joined string.

This would avoid creating a new 'names' field.
