### ISSUE TITLE
move from flask-script to flask.cli

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#729]
`flask-script` seems deprecated, `flask.cli` is built into flask, based on `click`.

http://flask.pocoo.org/docs/1.0/cli/

**Comment by RogerHaase** [comment]
Closing as dup of #1109 

Jinja2, flask, and werkzeug must be upgraded together to remove flask-script

**Comment by UlrichB22** [comment]
Maybe you can add a new label `flask 2.x` and keep this issue open as one of the subtasks.

**Comment by RogerHaase** [comment]
I meant to close this, must have clicked the wrong button. I am working on #1109, but slowly.

In addition to Jinja2, flask, and werkzeug there are upgrades to CLI, markupsafe, itsdangerous, maybe others.

**Comment by UlrichB22** [comment]
There is a prototype using flask cli in branch [github.com/UlrichB22/moin/tree/cli_preview](https://github.com/UlrichB22/moin/tree/cli_preview)

It offers the old flask-script based command `moin` and the new cli based command `moin2`.

This is only for testing and comparing the behavior of old and new version. For the final version I will rename the script module to cli and apply the changes. This will keep the history of each module. Command name will be `moin` again.

Migration to flask cli is not finished yet. Some commands and options like '--config' are still missing. I am still working on it. 
Please start with `moin2 --help` to find the available subcommands.

The main issue is fixing the codebase outside of the cli module. There is no request context and the flask cli seem to be more strikt in checking it. For example there is a function in converters/html_in that uses flash() to raise an error in the gui. Also app.py is mainly intended for the web application and needs some workarounds if called from cli.

Using a lot of try-blocks is not the preferred solution. I appreciate your comments and help. We can use the moin-devel mailing list for discussions. Please check, test and support.

**Comment by RogerHaase** [comment]
Or we could make notes here. I have cloned your repo. The "html" item is missing from the sample data, but adding an invalid tag to create a flash message in "help-en/html" works for me. Ditto for the flash messages issued by the "markdown_in" converter.

Will test more tomorrow.

**Comment by UlrichB22** [comment]
All commands inclusive import19 are now available, please see `moin2 --help`. The only problem is `dump-html`, it is broken because it relies too often on a valid session context. If you get a chance, can you help and try to fix it?

There are some minor changes or open topics:
- there is a new default flask command routes. I don't know if we should hide or deactivate and how to do it.
- there is no `moin2 moin` command :-( . Do we need it as an alias to `moin run`?
- Global option --config still need to be added and tested.

Next steps:
- move scripts folder to cli and merge changes, remove flask-script dependency
- update docs
- add tests 
- . . .
- continue with update to newest versions of flask, werkzeug and jinja2
