### ISSUE TITLE
quickinstall.py not updating tox environment?

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#894]
quickinstall.py attempts to update the tox virtualenv so the tests running on github merge will be same/similar to those running on a local development PC.

But output from end of quickinstall log now says:

    'tox' is not recognized as an internal or external command,
    operable program or batch file.

If you see errors on github merge that cannon be reproduced on your local development PC, a workaround is to delete the .tox directory in your repo root and rerun ./m tests,

**Comment by ThomasWaldmann** [comment]
somehow i guess i meanwhile rather tend to get rid of all env handling stuff in "m".

at the europython sprints, there was one developer for whom it took quite some time to get things set up due to having to read up on how to use "m" - guess he would have been quicker just creating the virtualenv and running `pip install -r requirements.txt` and `pip install -e .`, like most projects work instead of moin's special `m ...` which is only there in moin.

**Comment by RogerHaase** [comment]
I think we write code for different users. I write for non-programmers who want to set up a simple desktop wiki on Windows or maybe a free/paid account on pythonanywhere to discuss/document  some exotic topic (like rock art recording).

The reason quickinstall tries to update tox is because ~6 months ago the githup tox was magically updated several times and reported pep errors not identified on local tests. 

Maybe rather than try to update the tox environment, quickinstall should just delete the entire .tox directory and let the next run of ./m tests rebuild it.

**Comment by ThomasWaldmann** [comment]
The problem is not the target user group, but that the current way of scripting is maybe ok for some users using a github checkout but might not be suitable for packaging (pypi, other distributions). But guess I should make another issue about that.

**Comment by RogerHaase** [comment]
The original problem may have been caused by a failure to run ./m extras after creating a fresh clone. ./m extras installs tox in the virtualenv.
