### ISSUE TITLE
implement a typical installation and usage workflow

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#902]
## typical workflow

In the last years, I worked on quite some non-moin python projects (e.g. django-based, borgbackup, ...) and know what developers and python-package users typically expect as work flow when using a python package.

We should implement that, so that new moin users / developers do not waste time due to unusual workflow and feel alienated from minute one.

```
# 1. GET the software (from pypi, from linux package manager, from git, ...)
pip install [...] moin
# or:
# git clone moin ; cd moin ; pip install -r requirements.d/dev.txt ; pip install -e .
# apt install moin
# EXPECTATION from this step:
# the software is now installed and some "moin" cli command is in PATH
# and can be invoked to do something with it.

# 2. INSTANCE CREATION
# moin can be used to run one or multiple moin wiki instances on this machine.
# first we need a place to store stuff that is related to our first instance.
moin create-instance INSTANCE-PATH
# EXPECTATION:
# There is now some empty wiki instance in INSTANCE-PATH,
# including:
# - some configuration files
# - some directories for data, index, maybe logs, ...

# 3. configure the wiki
edit INSTANCE-PATH/wikiconfig.py

# 4. RUN the wiki
moin run INSTANCE-PATH  # use the builtin server
# alternatively:
# configure real web server to invoke moin via wsgi.
```

Currently, moin is not ready to do that:

After `pip install`, there is a `moin` command, but if one invokes it (without parameters), it tries to start the builtin server and fails with a traceback because there is no storage configuration.

## TODO

- do not try to start the wiki just with `moin` (use only `moin run` for that), rather show an overview of available `moin` subcommands.

- `m` and no `quickinstall.py` do not exist (and should not exist) in this scenario, but some functionality needed by production wiki admins should be moved from `m` to the `moin` command, so it can be used.

- functionality only needed by developers should stay in `m` and `quickinstall.py` for now.

**Comment by ThomasWaldmann** [comment]
hmm, maybe we don't need to **move** stuff from `quickinstall.py` to `moin` cli command - most stuff there are just convenience wrappers wrapping `moin` commands.

**Comment by ThomasWaldmann** [comment]
so, this mostly boils down to writing docs for normal users / admins.

**Comment by RogerHaase** [comment]
The only `m` command that is not in `moin` is `interwiki` which is used to update the interwiki map from `http://master19.moinmo.in/InterWikiMap?action=raw`. We should continue this until a better source is created. The immediate problem is the interwiki map is stored in contrib/interwiki/intermap.txt under version control and will not be copied to pypi. The interwiki.txt file should be moved to /src/moin/config/.

/src/moin/config/ is a convenient location for interwiki.txt because wikiconfig.py must also be moved, and the logical location for wikiconfig.py is /src/moin/config/.

So # 2. INSTANCE CREATION above will include copying wikiconfig.py and interwiki.txt to the instance directory, and creating an empty wiki. 

For developers, quickinstall.py must be modified to copy wikiconfig.py and interwiki.txt. A future simplification would include removing support for wikiconfig_local.py and wikiconfig_editme.py.
