### ISSUE TITLE
werkzeug 1.0.0 cannot import cached_property

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#951]
If quickinstall installs werkzeug 1.0.0, you must install older version:

    pip install werkzeug==0.16.1

**Comment by sblondon** [comment]
According to a warning displayed when `tox` runs, the `import` is done in flask-theme:

```
.tox/py37/lib/python3.7/site-packages/flask_theme/__init__.py:27
  /home/stephane/src/moin/.tox/py37/lib/python3.7/site-packages/flask_theme/__init__.py:27: DeprecationWarning: The import 'werkzeug.cached_property' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.utils import cached_property' instead.
    from werkzeug import cached_property
```

It's fixed in [upstream repository](https://github.com/liuliqiang/flask-theme). When a new release will be published in pypi.org, this error will disappear.
Updating the dependancy version from flask-theme should be the right fix.
